title: No Money To Cultivate Immortality
description: Unofficial Fan Translation
url: "https://thundergod95.github.io"
baseurl: "/nmtci"
lang: en
encoding: "utf-8"

plugins:
    - jekyll-sitemap
    - jekyll-minifier

defaults:
    - scope:
          path: "translations"
      values:
          layout: "chapter"
          sitemap: true

markdown: kramdown
kramdown:
    smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"]
    auto_ids: true
    parse_block_html: true
permalink: pretty

exclude:
    - scripts
    - README.md
    - LICENSE
    - bundled
    - assets/glossary.json
    - assets/glossary-schema.json
    - .github
